services:
  - type: web
    name: jen-paminta
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend wsgi:app -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "4000"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: jen_paminta
      - key: DB_USE_SSL
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false

